apiVersion: v1
kind: Service
metadata:
  name: web-gitaction-service
spec:
  type: NodePort  # ← Cambia esto (no LoadBalancer)
  selector:
    app: web-gitaction
  ports:
    - port: 80          # Puerto del servicio
      targetPort: 3000  # Puerto del contenedor (como en tu Dockerfile)
      nodePort: 30080   # Puerto en los nodos (opcional, rango 30000-32767)
